# logtype can take: debug, info, notice, warning, error, critical
# warning is the default
logtype = "debug"

[server]
port = 8090
location = "somewhere"

[picture]
# for RPi
# cmd = ""

# command to take picture
cmd = "raspistill -o /tmp/capture.jpg"