# logtype can take: debug, info, notice, warning, error, critical
# warning is the default
logtype = "notice"

# motionProgram is the program which use to detect motion. You should put full path:
# for example: motionProgram = "/usr/bin/motion"
# another example: motionProgram = "/usr/bin/hogc"
# You can find full path for example in console with: which motion
[default]
motionProgram = "motion"

[server]
port = 8090
location = "somewhere"
# method can take: motionOnly, tmpfs
method = ""
# You need tmpfs for stream function in tmpfs method. It will be mounted automatically with fstab
tmpfsPath = ""
# File to say if alarm is started or not.
# Becarefull with /tmp folder. At reboot, all files and folder in /tmp will be removed
startalarm = ""

[raspistill]
# width of camera
camWidth = 640
# height of camera
camHeight = 480
# timeLaps is a time in millisecond which used to refresh picture
timeLaps = 450
# Allows to rotate image, only for RPi cam
angle = 0

# Only with method motionOnly since with tmpfs, it's using raspistill and width
# and height will be the size of raspistill even if streamWidth and streamHeight
# were different
[mjpgstreamer]
streamWidth = 320
streamHeight = 240

#
# To use GPIO, you must install wiringPi or similar. It using "gpio" program
#
# Be careful, you must use the wpi position (gpio readall), not the physical position or bcm.
# For example, 0 corresponds to physical location 11
# At start, gpio0 list will be set to 0 and gpio1 list set to 1
# At stop, the same lists will be toggle (gpio0 will be set to 1 and gpio1 set to 0)

[atstart]
# list of gpio that will be set to 0 at startup
gpioto0 = []
# list of gpio that will be set to 1 at startup
gpioto1 = []
